#### python常用内置函数复习

In [ ]:
# print('abc')
# print(len([1,2,3]))
# for value in [0,2,4,6,8]:
#   print(value)

# for i, value in enumerate([0,2,4,6,8]):
#   print(i, value)


0 0
1 2
2 4
3 6
4 8


In [ ]:
### abs(): 取绝对值
# print(abs(-2.3))
# ### round(): 四舍五入
# print(round(3.5))
# ### sum():求和, 参数为可迭代对象，如list
# print(sum([4,3]))
# ### len():求长度，参数为可迭代对象，如list
# print(len([1,2,3]))
# ### sorted():排序，参数为可迭代对象
# print(sorted([3,2,5]))


[2, 3, 5]


### Python库调用：numpy、pandas、matplotlib

numpy

In [11]:
import numpy as np ## 导入


创建数组

In [18]:
# a = np.array([1,2,3], dtype=np.int32)  #指定类型
a = np.array([1,2,3], dtype=np.float32)  #指定类型
# a
a.dtype


dtype('float32')

In [ ]:
# ## 创建特定数据
# a = np.zeros(shape=(3,4))  ## 创建全是0数组
# a = np.ones(shape=(3,4), dtype=np.int32)  ## 创建全是0数组
# a = np.arange(10,20,3)  ## 创建连续数组
# a = np.linspace(1,10,20)  ## 创建连续数组
print(a)


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


numpy对象属性: 维数（ndim)，形状（shape），元素个数（size）

In [26]:
a = np.array([[1,2,3],
              [3,4,5]])
print(a.ndim)
print(a.shape)
print(a.size)


2
(2, 3)
6


基本运算-1

In [33]:
# ## 基本运算(一维)
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
# c = a+b
# c = a-b
# c = a*b
c = a**b
print(c)


[   1    8   81 1024]


In [36]:
# ## 简单统计:平均值、最大值、最小值、求和、标准差。
d = np.mean(c)
d = np.max(c)
d = np.min(c)
d = np.sum(c)
d = np.std(c)
print(d)

431.5532991416008


In [38]:
## 基本运算(二维)
a = np.array([[1,2],
              [2,3]])
b = np.array([[3,4],
              [4,5]])
c = a@b  ## 矩阵乘
# c = a*b  ## 点乘
print(c)

[[11 14]
 [18 23]]


In [ ]:
## 简单统计(二维):平均值、最大值、最小值、求和、标准差
d = np.mean(c)
d = np.mean(c, axis=0)  ## 行维度上取平均
print(d)

[14.5 18.5]


索引

In [42]:
a = np.arange(1,10).reshape(3,3)
print(a)
a[0, 1]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

合并

In [46]:
# ## 一维
a = np.array([1,2,3])
# print(a)
b = np.array([4,5,6])
# c = np.hstack((a,b))
c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [57]:
a = np.array([1,2,3]).reshape(1,3)
b = np.array([4,5,6]).reshape(1,3)
# a
c = np.concatenate((a,b), axis=0)
print(c)


[[1 2 3]
 [4 5 6]]


赋值与浅复制

In [63]:
# ### 赋值
a = np.array([1,2,3])
b = a    ## 新旧变量指向同一内存，不是值的复制。
# print(id(a), id(b))
# print(a, b)
a[0] = 11
print(a, b)
b[0] = 22
print(a, b)


[11  2  3] [11  2  3]
[22  2  3] [22  2  3]


In [69]:
# ### 复制(浅复制)
a = np.array([1,2,3])
b = a.copy()    ## 复制a地址所指向的数据，b变量指向的是复制数据的新地址。
print(id(a), id(b))
print(a, b)
a[0] = 11
# print(a, b)
b[0] = 22
print(a, b)


1497836469776 1497836469968
[1 2 3] [1 2 3]
[11  2  3] [22  2  3]
